
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "visibilityworkshop.fullname" . }}
spec:
  maxReplicas: {{ .Values.maxReplicas}}
  minReplicas: {{ .Values.minReplicas}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "visibilityworkshop.fullname" . }}
  targetCPUUtilizationPercentage: 90

