
apiVersion: v1
kind: Service
metadata:
  name: {{ include "visibilityworkshop.name" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
  - name: grpc
    port: 9090
  - name: prometheus
    port: 2112
  selector:
    app: {{ include "visibilityworkshop.name" . }}
  sessionAffinity: None
status:
  loadBalancer: {}

